import os
import time
import random
import shutil
from dotenv import load_dotenv

# --- 🛠️ FIX FOR PILLOW 10+ CRASH (MUST BE AT TOP) ---
import PIL.Image

if not hasattr(PIL.Image, "ANTIALIAS"):
    PIL.Image.ANTIALIAS = PIL.Image.LANCZOS
# ----------------------------------------------------

# Instagram Login
from login import login_user

# --- CONFIGURATION ---
load_dotenv()

# Folders
OUTPUT_DIR = "output"
IMAGES_DIR = "images"

# Constant Caption
FIXED_CAPTION = """#lamborghini #carsofinstagram #huracan #lambo #lamborghinihuracan
#porsche #carsofinstagram #gt3rs #992gt3rs #porsche911 #bmw #bmwm3 #bmws1000rr #bmwnation
#bmw #bmws1000rr #bmwm #bmwperformance

#bmw #bmws1000rr #bmwnation #bmwm3
#bmw #bmwm3 #f80m3 #snow #carsofinstagram

#bmw #carsofinstagram #bmwfans #bmwm3"""


def ensure_folders():
    """Ensures output folder exists but DOES NOT delete contents."""
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    print("📂 Directories verified.")


# --- STEP 4: UPLOAD TO INSTAGRAM ---
def upload_reel(video_path, caption):
    # Determine the thumbnail path (assuming it's generated by instagrapi or we need to generate it)
    # The original code generated a thumbnail using video_editor.
    # Since we are deleting video_editor, we rely on instagrapi's auto-thumbnail or a simple fallback.
    # Instagrapi's clip_upload can often handle it, but having a thumbnail is better.
    # For now, we'll try uploading without explicit thumbnail generation if video_editor is gone,
    # OR we allow instagrapi to generate it.

    print("🚀 Connecting to Instagram...")
    cl = login_user()
    if not cl:
        print("❌ Login failed. Video skipped.")
        return False

    # VERIFY we're actually logged in
    try:
        user = cl.account_info()
        print(f"✅ Logged in as: @{user.username}")
    except Exception as e:
        print(f"❌ Not actually logged in! Error: {e}")
        print(
            "💡 Get fresh INSTA_SESSIONID from browser cookies (see FIX_INSTAGRAM_LOGIN.md)"
        )
        return False

    print(f"📤 Uploading reel to Instagram: {os.path.basename(video_path)}")

    try:
        # Note: We are not passing a custom thumbnail path here because we removed the generator.
        # Instagrapi usually handles this or generates one.
        media = cl.clip_upload(video_path, caption=caption)

        # Success
        if media and hasattr(media, "code"):
            print(f"\n🎉 SUCCESS! REEL POSTED!")
            print(f"📱 Code: {media.code}")
            print(f"🔗 URL: https://www.instagram.com/reel/{media.code}/")
            print(f"👀 Profile: https://www.instagram.com/{user.username}/")
            return True
        else:
            print("⚠️ Upload returned but no media code")
            return False

    except Exception as e:
        error_str = str(e)

        # Sometimes instagrapi throws pydantic errors even when upload succeeds
        if "pydantic" in error_str.lower() or "validation" in error_str.lower():
            print("\n✅ Upload likely SUCCEEDED (pydantic parsing error)")
            print(f"👀 Check your profile: https://www.instagram.com/{user.username}/")
            return True  # Treat as success to delete the file

        # Real errors
        print(f"\n❌ UPLOAD FAILED: {error_str}")

        if "login_required" in error_str.lower():
            print("\n💡 FIX: Session expired! Get fresh sessionid from browser")
        elif "challenge" in error_str.lower():
            print("\n💡 FIX: Complete verification in Instagram app")
        elif "spam" in error_str.lower() or "limit" in error_str.lower():
            print("\n💡 FIX: Wait 1-2 hours (posting too fast)")

        return False


def get_video_files():
    """Returns a list of video files in the output directory."""
    if not os.path.exists(OUTPUT_DIR):
        return []

    video_extensions = (".mp4", ".mov", ".mkv", ".avi")
    files = [
        os.path.join(OUTPUT_DIR, f)
        for f in os.listdir(OUTPUT_DIR)
        if f.lower().endswith(video_extensions)
    ]
    return files


# --- MAIN LOOP ---
if __name__ == "__main__":
    try:
        ensure_folders()

        videos = get_video_files()

        if not videos:
            print(f"⚠️ No videos found in '{OUTPUT_DIR}' folder.")
            print("   Please add video files (.mp4, .mov) to the output folder.")
            exit()

        print(f"� Found {len(videos)} videos in queue.")

        # Pick one random video
        selected_video = random.choice(videos)
        print(f"👉 Selected video: {selected_video}")

        # Upload
        success = upload_reel(selected_video, FIXED_CAPTION)

        # Delete if successful
        if success:
            try:
                os.remove(selected_video)
                print(f"🗑️ Deleted uploaded video: {selected_video}")
            except Exception as del_err:
                print(f"⚠️ Failed to delete video: {del_err}")
        else:
            print("⚠️ Video NOT deleted because upload failed.")

    except Exception as e:
        print(f"\n❌ FATAL ERROR: {e}")
